# Generated by Django 4.2.6 on 2024-02-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.TextField(max_length=100)),
                ('description', models.DateField(max_length=250)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
